config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles
  get "signup", to: "users#new"
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 6, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase }
  has_many :articles

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 125 }, format: { with: VALID_EMAIL_REGEX}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  
  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def new
  @article = Article.new
  end

  def create
    # render plain: params[:article]
    @article = Article.new(article_params)
    @article.user = User.first
    # render plain: @article or @article.inspect
    if @article.save
      # redirect_to article_path(@article)
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else
      render "new"
    end
  
  end

    def edit
      # byebug
    end

    def update
      if @article.update(article_params)
        flash[:notice] = "The article was updated successfully."
        redirect_to @article
      else
        render "edit"
      end

  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end


  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    # byebug
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the Alpha Blog #{ @user.username }, you have successfully signed up."
      redirect_to articles_path
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated."
      redirect_to @user
    else
      render "edit"
    end
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]  
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <% @articles.each do |article| %>
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic font-weight-bold">
            <% if article.user %>
              By <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "Show", article_path(article), class: "btn btn-outline-success" %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-warning" %>
            <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>            
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, Updated <%= time_ago_in_words(article.updated_at) %> ago</small>>
          </div>
        </div>
      </div>
    <% end %>
  <div>
</div>

app/views/articles/_form.html.erb
<div class="container mt-4">  

  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj: @article %>
      <%= form_with(model: @article, class: "shadow mb-3 p-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
            <%= f.label :title, class: "col-2 col-form-label text-light" %>          
            <%= f.text_field :title, class: "col-9 form-control shadow rounded", placeholder: "Title of article" %>          
        </div>

        <div class="form-group row">          
            <%= f.label :description, class: "col-2 col-form-label text-light" %>          
            <%= f.text_area :description, rows: 7, class: "col-9 form-control shadow rounded", placeholder: "Description of article" %>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
        
    </div>
      <% end %>
    
      <%= link_to "[ Cancel and return to articles listing ]", articles_path(@article), class: "text-info" %>
  
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center my-3">Edit article!</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1 class="text-center my-4">Articles listing page</h1>

<div class="flickr_pagination mb-2">  
  <%= will_paginate @articles, :container => false %>
</div>

<%= render "article" %>

<div class="flickr_pagination my-2">  
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article!</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4">Article's detail</h1>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic font-weight-bold">
          By <%= @article.user.username %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        </div>
        <div class="card-body">          
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>          
          <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-warning" %>
          <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, Updated <%= time_ago_in_words(@article.updated_at) %> ago</small>>
        </div>
      </div>
    </div>    
  <div>
</div>

app/views/layouts/_footer.html.erb
<footer class="py-4 bg-dark text-white fixed-bottom">
  <div class="container text-center">
    <small>Copyright &copy; Your Website</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <%= link_to "List of the articles", articles_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render "layouts/navbar" %>
    
    <%= render "layouts/messages" %>

    <%= yield %>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/_jumbotron.html.erb
<div class="container my-5">
  <div class="jumbotron text-center text-white">
    <h1 class="display-4 text-center">Alpha Blog</h1>
    <p class="lead">Just blogging!</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

app/views/pages/about.html.erb
<h1 class="text-center my-3">This is the about page</h1>

<div class="container">
  <%= link_to "Articles listing", articles_path %> |
  <%= link_to "Homepage", root_path %>
</div>

app/views/pages/home.html.erb
<%= render "jumbotron" %>  

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented <%= obj.class.name.downcase %> from being saved!</h4>
    <ul>
      <%= obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container mt-4">  

  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj: @user %>
      <%= form_with(model: @user, class: "shadow mb-3 p-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
            <%= f.label :username, class: "col-2 col-form-label text-light" %>          
            <%= f.text_field :username, class: "col-9 form-control shadow rounded", placeholder: "Enter a username" %>          
        </div>

        <div class="form-group row">          
            <%= f.label :email, class: "col-2 col-form-label text-light" %>          
            <%= f.email_field :email, class: "col-9 form-control shadow rounded", placeholder: "Enter your email address" %>
        </div>

        <div class="form-group row">          
            <%= f.label :password, class: "col-2 col-form-label text-light" %>          
            <%= f.password_field :password, class: "col-9 form-control shadow rounded", placeholder: "Choose a password" %>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update user", class: "btn btn-outline-light btn-lg") %>
        </div>
        
    </div>
      <% end %>
    
      <%= link_to "[ Cancel and return to articles listing ]", articles_path(@article), class: "text-info" %>
  
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile!</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="flickr_pagination mb-2">  
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <div class="row justify-content-md-center">
    <% @users.each do |user| %>
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic font-weight-bold">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "Show profile", user, class: "btn btn-outline-success" %>
            <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-warning" %>            
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>>
          </div>
        </div>
      </div>
    <% end %>
  <div>
</div>

<div class="flickr_pagination mb-2">  
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog!</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<div class="flickr_pagination mb-2">  
  <%= will_paginate @articles, :container => false %>
</div>

<div class="text-center mt-4">
  <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
</div>

<h3 class="text-center mt-4">Articles</h3>
<%= render "articles/article" %>

<div class="flickr_pagination mb-2">  
  <%= will_paginate @articles, :container => false %>
</div>